// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

namespace backend.Migrations.Cups
{
    [DbContext(typeof(CupsContext))]
    partial class CupsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("backend.Models.Cups", b =>
                {
                    b.Property<int>("CupsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CupsName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CupsPhotoFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CupsYear")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CupsId");

                    b.ToTable("Cups");
                });
#pragma warning restore 612, 618
        }
    }
}
