// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

namespace backend.Migrations.Legends
{
    [DbContext(typeof(LegendsContext))]
    [Migration("20220619070321_LegendsMigration")]
    partial class LegendsMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("backend.Models.Legends", b =>
                {
                    b.Property<int>("LegendsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LegendsApps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegendsName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegendsPhotoFileName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LegendsId");

                    b.ToTable("Legends");
                });
#pragma warning restore 612, 618
        }
    }
}
